title: Climbuddy Blog
author: Team Climbuddy
email: contact@climbuddy.com
description: >- # this means to ignore newlines until "baseurl:"
  Updates / articles about Climbuddy.com.
baseurl: ""
url: "https://blog.climbuddy.com"
twitter_username: Climbuddy
github_username: Climbuddy
instagram_username: Climbuddy
rss: RSS

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jektex

permalink: /:title/

exclude:
  - ignored
