title: Climbuddy Blog
author: Tomáš & Matěj
email: contact@climbuddy.com
description: >- # this means to ignore newlines until "baseurl:"
  Updates / articles about Climbuddy.com.
baseurl: ""
url: "https://blog.climbuddy.com"
twitter_username: Climbuddy
github_username:  Climbuddy

# Build settings
theme: minima
plugins:
  - jekyll-feed

permalink: /:title/
